export const GET_USERS_INFO = 'GET_USERS_INFO'
export const USER_AUTH = 'USER_AUTH'
export const USER_LOGOUT = 'USER_LOGOUT'
export const LOAD_INDICATOR = 'LOAD_INDICATOR'


export const GET_FORM_KITCHEN = 'GET_FORM_KITCHEN'
export const REQUEST_KITCHEN = 'REQUEST_KITCHEN'
export const CLEAR_REQUEST_KITCHEN = 'CLEAR_REQUEST_KITCHEN'
