export const GET_USERS_INFO = 'GET_USERS_INFO'
export const USER_AUTH = 'USER_AUTH'
export const USER_LOGOUT = 'USER_LOGOUT'


export const GET_FORM_KITCHEN = 'GET_FORM_KITCHEN'
export const GET_FORM_BAR = 'GET_FORM_BAR'
export const GET_FORM_OFFICE = 'GET_FORM_OFFICE'
export const REQUEST_KITCHEN = 'REQUEST_KITCHEN'
export const REQUEST_BAR = 'REQUEST_BAR'
export const REQUEST_OFFICE = 'REQUEST_OFFICE'
export const CLEAR_REQUEST_KITCHEN = 'CLEAR_REQUEST_KITCHEN'
export const CLEAR_REQUEST_BAR = 'CLEAR_REQUEST_BAR'
export const CLEAR_REQUEST_OFFICE = 'CLEAR_REQUEST_OFFICE'

